INSERT INTO `baremo` (`id`, `name`, `active`) VALUES (57, '3ro y 4to secundaria', '1')
INSERT INTO `baremo` (`id`, `name`, `active`) VALUES (58, '5ro y 6to secundaria', '1')


INSERT INTO `question` (`item_order`, `question`, `type_question_id`) VALUES 
(1, 'Apagar incendios o prevenirlos, proteger o salvar a las personas en los mismos.', 6),
(2, 'Ser ingeniero en Electrónica.', 6),
(3, 'Realizar tareas de especialista en diversos campos de la Informática; llevar a cabo trabajos de programación, análisis y arquitectura de computadores.', 6),
(4, 'Trabajar como publicista.', 6),
(5, 'Asesorar y tratar a las personas con problemas de alimentación, elaborando la dieta adecuada para cada paciente.', 6),
(6, 'Ser criminólogo.', 6),
(7, 'Proyectar edificios y supervisar la construcción de los mismos; proyectar el desarrollo de zonas urbanas; participar en la ordenación estética de jardines.', 6),
(8, 'Ser gestor administrativo.', 6),
(9, 'Conservar y restaurar bienes culturales (esculturas, cuadros, elementos arqueológicos, documentos, etc.) sin alterarlos.', 6),
(10, 'Trabajar como técnico en animación turística.', 6),
(11, 'Rescatar a personas que se encuentren en situaciones problemáticas en el mar, ríos, pantanos, etc. Practicarles los primeros auxilios.', 6),
(12, 'Ser ingeniero de montes', 6),
(13, 'Buscar y redactar noticias para publicarlas en la prensa escrita o para difundirlas por radio, televisión u otros medios.', 6),
(14, 'Trabajar como restaurador de bienes culturales', 6),
(15, 'Formar parte de una orquesta o actuar como solista tocando un instrumento musical (piano, violín, guitarra, etc.)', 6),
(16, 'Ser bombero.', 6),
(17, 'Analizar e investigar la actuación del hombre en sus aspectos social y evolutivo a lo largo del tiempo y difundir estas investigaciones como profesor o escribiendo artículos o libros.', 6),
(18, 'Ser dietista (Grado en Nutrición Humana).', 6),
(19, 'Realizar las tareas necesarias para garantizar la seguridad de los ciudadanos y asegurar el libre ejercicio de las libertades.', 6),
(20, 'Ser ingeniero en Informática.', 6),
(21, 'Dar recitales o conciertos interpretando canciones clásicas o modernas, actuando como solista o formando parte de un grupo.', 6),
(22, 'Trabajar en Comunicación audiovisual.', 6),
(23, 'Representar a empresas, trabajadores o particulares ante los tribunales de lo social. Trabajaren asuntos relacionados con la búsqueda de empleo, organización del trabajo o gestión de personal.', 6),
(24, 'Trabajar como técnico en turismo.', 6),
(25, 'Aplicar los conocimientos informáticos sobre sistemas operativos y tecnología de la programación en la realización de software de gestión para empresas. Analizar proyectos informáticos para las mismas.', 6),
(26, 'Ser músico instrumentista', 6),
(27, 'Realizar trabajos técnicos, científicos o de mando, relacionados con los fines de ejercito, formando parte de este', 6),
(28, 'Trabajar como animador de actividades físicas y deportivas.', 6),
(29, 'Intervenir ante los tribunales de justicia en nombre de la ley, representando a una persona o al estado. Asesorar y defender a personas o entidades en todo lo relativo a sus intereses jurídicos.', 6),
(30, 'Trabajar como técnico en información turística.', 6),
(31, 'Organizar explotaciones agrícolas o agropecuarias para obtener mejores variedades de vegetales y mejorar las razas animales. Proyectar maquinaria agrícola.', 6),
(32, 'Trabajar en el campo de los Recursos Humanos.', 6),
(33, 'Establecer comunidades de propietarios, participando en la elaboración de sus estatutos, asistir a las reuniones de las mismas y elaborar las actas. Formalizar contratos.', 6),
(34, 'Trabajar como técnico superior en restauración.', 6),
(35, 'Dirigir la realización material en las obras de construcción de edificios y controlar los materiales empleados en estas. Hacer que las obras se ajusten al proyecto.', 6),
(36, 'Trabajar como conductor de actividades deportivas en el medio natural.', 6),
(37, 'Curar algunas enfermedades del aparato locomotor o del sistema nervioso (parálisis, torceduras, etc.) mediante técnicas y medios naturales, mecánicos o físicos.', 6),
(38, 'Trabajar como profesional de las Ciencias de la Actividad Física.', 6),
(39, 'Idear, preparar y dirigir programas de animación cultural, estableciendo las actividades recursos y documentación necesarias para llevarlos a cabo.', 6),
(40, 'Ser administrador de fincas', 6),
(41, 'Organizar actividades físicas o deportivas, enseñar juegos o actividades físicas en centros escolares, centros de salud, etc., adaptándolas a las características de los participantes.', 6),
(42, 'Ser musicólogo', 6),
(43, 'Trabajar en la educación de adultos, utilizando recursos didácticos y nuevas tecnologías o en la integración social de personas desadaptadas o discapacitados físicos o psíquicos.', 6),
(44, 'Ser ingeniero técnico en Informática de Gestión', 6),
(45, 'Dedicarse a la conservación de recursos naturales, aplicando conocimientos científicos sobre el medio ambiente y sus bases físicas y químicas. Analizar los fenómenos meteorológicos y realizar predicciones.', 6),
(46, 'Ser economista', 6),
(47, 'Trabajar en explotaciones ganaderas ocupándose de la alimentación e higiene de los animales destinados a la producción de alimentos (leche, carne, etc.)', 6),
(48, 'Ejercer la profesión de historiador.', 6),
(49, 'Realizar, en el Ejército, trabajos de especialista en mecánica, electricidad, electrónica, automoción, etc.', 6),
(50, 'Trabajar como técnico superior en administración de sistemas informáticos.', 6),
(51, 'Aplicar los conocimientos profesionales para registrar, reproducir y captar sonidos en producciones musicales o de espectáculos de cualquier tipo, garantizando una buena calidad técnica.', 6);

INSERT INTO `question` (`item_order`, `question`, `type_question_id`) VALUES 
(52, 'Ser cantante.', 6),
(53, 'Realizar trámites (seguros, permisos de conducir, de armas, etc.) para empresas o particulares.', 6),
(54, 'Ser veterinario.', 6),
(55, 'Aplicar conocimientos de Informática, Electrónica y Telecomunicaciones para el tratamiento gráfico de datos.', 6),
(56, 'Ser controlador aéreo.', 6),
(57, 'Enseñar a alumnos con necesidades especiales (físicas o psíquicas), valorando la situación de cada alumno para adaptar a ese dato la enseñanza.', 6),
(58, 'Trabajar como técnico superior en alojamiento.', 6),
(59, 'Estudiar los seres vivos y realizar trabajos en campos como la Botánica, la Zoología o la Genética. Aplicar sus conocimientos en diversas industrias (sanitaria, alimentación, conservera, etc.).', 6),
(60, 'Ser dibujante, ilustrador de publicaciones', 6),
(61, 'Bailar en representaciones públicas, interpretando danza clásica o moderna, en teatros, festivales, etc.', 6),
(62, 'Ser astrónomo', 6),
(63, 'Realizar trabajos de informática aplicada a las comunicaciones.', 6),
(64, 'Trabajar como técnico en explotaciones ganaderas.', 6),
(65, 'Estudiar la Tierra y sus componentes. Tratar de localizar recursos naturales, como petróleo, gases y otros minerales, para su explotación.', 6),
(66, 'Trabajar como maestro especialista en Educación Física.', 6),
(67, 'Utilizar los conocimientos sobre masaje y anatomía humana para ayudar a los deportistas a recuperarse de las lesiones relacionadas con su actividad deportiva.', 6),
(68, 'Trabajar como vigilante jurado', 6),
(69, 'Cooperar en la educación de niños de O a 3  años contribuyendo a la mejora de sus hábitos de alimentación, higiene y seguridad y favoreciendo el desarrollo de su autonomía.', 6),
(70, 'Ser oficial de carrera del Ejército.', 6),
(71, 'Trabajar en centros de cultivo de especies acuáticas vegetales o animales (acuicultura). Investigar para la conservación y preservación de recursos marinos.', 6),
(72, 'Trabajar en el ámbito de las Ciencias Actuariales y Financieras.', 6),
(73, 'Aplicar conocimientos científicos trabajando en laboratorios donde se preparan medicamentos. Atender un establecimiento de farmacia, informando a los clientes sobre los efectos de los medicamentos y su utilización.', 6),
(74, 'Ser geólogo.', 6),
(75, 'Elaborar la información para presentarla en los medios de comunicación audiovisual.', 6),
(76, 'Ser un profesional dedicado a las Ciencias del Mar', 6),
(77, 'Desarrollar proyectos o trabajos de electrónica aplicada a la industria, como robotización, organización de plantas industriales o diseño de circuitos electrónicos.', 6),
(78, 'Trabajar como diseñador de interiores.', 6),
(79, 'Potenciar los espacios naturales y su utilización y tomar decisiones sobre la conservación y repoblación de bosques y la prevención de incendios forestales.', 6),
(80, 'Ser especialista en Telemática (combinación de servicios de informática y telecomunicación).', 6),
(81, 'Estudiar los fenómenos del firmamento y aplicar estos conocimientos a la navegación o a la utilización del espacio.', 6),
(82, 'Ser bailarín.', 6),
(83, 'Comprar, vender o alquilar casas, pisos o solares; estimar el valor de los mismos y asesorar a los propietarios.', 6),
(84, 'Ser técnico deportivo', 6),
(85, 'Investigar y analizar la historia de la música, sus técnicas y métodos.', 6),
(86, 'Trabajar como técnico en salvamento acuático', 6),
(87, 'Diseñar instalaciones relacionadas con las comunicaciones (telefonía, radio, televisión, radar, etc.) en diversos campos (industria, defensa, control aéreo, etc.).', 6),
(88, 'Trabajar como pedagogo.', 6),
(89, 'Aplicar conocimientos profesionales para resol ver problemas relacionados con los trabajadores de una empresa. Asesorar en conflictos laborales.', 6),
(90, 'Trabajar como técnico en artes plásticas y diseño.', 6),
(91, 'Estudiar la sociedad, los grupos humanos y sus relaciones y aplicar estos conocimientos realizando análisis sociológicos (encuestas, cuestionarios, etc.) o cooperando a la solución de conflictos.', 6),
(92, 'Trabajar como técnico de sonido.', 6),
(93, 'Dirigir fincas, tratar de aumentar la productividad de granjas o explotaciones agrícolas.', 6),
(94, 'Investigar los fundamentos de la religión católica; estudiar y analizar textos escritos, restos arqueológicos y tradiciones.', 6),
(95, 'Ser ingeniero técnico agrícola.', 6),
(96, 'Ejercer la profesión de trabajador social.', 6),
(97, 'Diseñar y elaborar productos relacionados con la moda: tejidos, ropa, joyería, bisutería, calzado, etc.', 6),
(98, 'Trabajar como masajista deportivo.', 6),
(99, 'Realizar tareas de vigilancia y protección del medio ambiente en bosques, jardines o parques e intervenir en la plantación de árboles o arbustos y en la conservación de bosques.', 6),
(100, 'Ser abogado.', 6);

INSERT INTO `question` (`item_order`, `question`, `type_question_id`) VALUES 
(101, 'Impartir las enseñanzas de educación física, contribuir a la mejora de las capacidades físicas de los alumnos de educación infantil y primaria y a su desarrollo personal.', 6),
(102, 'Trabajar en el campo de las Relaciones Laborales.', 6),
(103, 'Diseñar campañas publicitarias para dar a conocer un producto y lograr su aceptación o para difundir mensajes institucionales sobre temas como sanidad, circulación (tráfico) o energía.', 6),
(104, 'Trabajar como fisioterapeuta.', 6),
(105, 'Realizar las tareas relacionadas con la ordenación y la seguridad del tráfico aéreo en aeropuertos civiles.', 6),
(106, 'Ser ceramista.', 6),
(107, 'Realizar proyectos para la construcción de puentes, carreteras, aeropuertos, puertos o vías férreas; supervisar la construcción de dichas obras.', 6),
(108, 'Ser diplomático (embajador).', 6),
(109, 'Aplicar pruebas psicológicas para evaluar la inteligencia, aptitudes y personalidad de los alumnos; aconsejar técnicas para resolver problemas personales, de aprendizaje o de adaptación en la escuela.', 6),
(110, 'Ser ingeniero de Telecomunicación.', 6),
(111, 'Establecer destinos turísticos, atender y guiar a grupos de visitantes dominando, al menos, dos idiomas extranjeros para comunicarse con ellos.', 6),
(112, 'Trabajar en Enfermería.', 6),
(113, 'Colaborar con personas o familias para solucionar problemas de tipo social o personal (tratamientos médicos, falta de adaptación, etc.) o prestar servicios sociales en escuelas infantiles, residencias de mayores, hospitales, etc.', 6),
(114, 'Ser policía.', 6),
(115, 'Aplicar los conocimientos sobre las distintas manifestaciones artísticas dando clases de arte, trabajando en galerías de arte o escribiendo artículos o crítica en publicaciones.', 6),
(116, 'Trabajar como ingeniero agrónomo.', 6),
(117, 'Emplear técnicas de expresión gráfica para rea lizar ilustraciones en libros infantiles, fantásticos o científicos.', 6),
(118, 'Ser agente de la propiedad inmobiliaria.', 6),
(119, 'Representar al propio país en otros países, como embajador o trabajando en embajadas o consulados.', 6),
(120, 'Ser ingeniero de caminos (ingeniero civil).', 6),
(121, 'Asesorar sobre aspectos de la actividad física y el deporte en centros escolares o deportivos. Trabajar en temas deportivos en equipos, colegios, polideportivos, etc.', 6),
(122, 'Ser actor profesional.', 6),
(123, 'Investigar las propiedades de la materia y aplicar estas investigaciones a la creación de materiales y productos para la medicina, la agricultura, la alimentación y otras industrias.', 6),
(124, 'Ser diseñador especialista en moda.', 6),
(125, 'Prevenir, diagnosticar y tratar las enfermedades que padezcan los animales y estudiar los aspectos relativos a la cría y reproducción de los mismos.', 6),
(126, 'Ejercer la profesión de sociólogo.', 6),
(127, 'Dirigir o administrar restaurantes; crear productos gastronómicos para ofrecerlos a los clientes', 6),
(128, 'Ser arquitecto.', 6),
(129, 'Entrenar a deportistas o equipos para perfeccionar sus conocimientos y aptitudes y mejorar la práctica del deporte.', 6),
(130, 'Ser químico', 6),
(131, 'Crear piezas de cerámica, investigar técnicas o estilos relativos a este trabajo.', 6),
(132, 'Ser farmacéutico', 6),
(133, 'Obtener imágenes por medio de fotografía, vídeo o cámara cinematográfica y presentarlas en cualquier soporte. Iluminar espacios escénicos.', 6),
(134, 'Trabajar como maestro en Educación Especial.', 6),
(135, 'Aplicar los conocimientos de la anatomía, las funciones y el comportamiento de las personas sanas y enfermas para establecer, con métodos científicos, el diagnóstico clínico y el tratamiento de las enfermedades.', 6),
(136, 'Trabajar como tripulante de cabina de pasajeros o auxiliar de barco.', 6),
(137, 'Trabajar asesorando a las Fuerzas de Seguridad, en temas referentes a comportamientos criminales, analizando los hechos y su relación el medio social y cultural del delincuente.', 6),
(138, 'Trabajar como técnico superior en desarrollo de aplicaciones informáticas.', 6),
(139, 'Organizar todo lo necesario para recibir a los clientes de un hotel; supervisar los servicios del mismo que se relacionan con la acogida y atención al cliente (recepción, conserjería, etc.).', 6),
(140, 'Trabajar como educador social.', 6),
(141, 'Participar en el diseño de aplicaciones informáticas realizando la programación de las mismas de acuerdo con los requisitos y especificaciones establecidos.', 6),
(142, 'Trabajar en el ámbito de las Ciencias Ambientales.', 6),
(143, 'Aplicar los conocimientos de medicina al tratamiento de enfermedades dentales, localizar lesiones en la dentadura, hacer empastes, etc.', 6),
(144, 'Ser técnico de imagen', 6),
(145, 'Hacer averiguaciones e informar a jueces, policías y otros profesionales sobre los aspectos relacionados con comportamientos delictivos', 6),
(146, 'Ejercer la profesión de filólogo.', 6),
(147, 'Dirigir a personas o grupos en recorridos por senderos o zonas de montaña, a pie, en bicicleta o a caballo, en condiciones de seguridad.', 6),
(148, 'Ser biólogo.', 6),
(149, 'Establecer y manejar los sistemas informáticos que sirven de base para la administración y la gestión de una empresa o facilitar la utilización de paquetes informáticos de tipo general.', 6),
(150, 'Ser periodista', 6);

INSERT INTO `question` (`item_order`, `question`, `type_question_id`) VALUES 
(151, 'Enseñar a realizar un deporte determinado y procurar el perfeccionamiento del mismo.', 6),
(152, 'Ser arquitecto técnico (aparejador).', 6),
(153, 'Realizar los planes establecidos para la comercialización de productos. Organizar las secciones de ventas en empresas comercia/es o dirigir un establecimiento.', 6),
(154, 'Trabajar como Grado en multimedia.', 6),
(155, 'Actuar en representaciones teatrales, de cine o televisión, interpretando un personaje.', 6),
(156, 'Ser entrenador deportivo.', 6),
(157, 'Estudiar los procesos y técnicas de los medios audiovisuales y los elementos que intervienen en ellos. Elaborar la información para su difusión en estos medios.', 6),
(158, 'Ser odontólogo (dentista).', 6),
(159, 'Interpretar y traducir textos, aplicando los conocimientos lingüísticos, teóricos, prácticos y culturales propios de la lengua en que están escritos.', 6),
(160, 'Ser director-realizador de medios audiovisuales.', 6),
(161, 'Procurar la mejora del turismo incluyendo actividades culturales o de interés humano en las que el turista participe, destacando los aspectos que lo hagan más atractivo.', 6),
(162, 'Trabajar como psicólogo escolar.', 6),
(163, 'Doblar las voces de actores extranjeros para las versiones traducidas de películas de cine o de televisión.', 6),
(164, 'Trabajar como técnico en educación infantil.', 6),
(165, 'Crear diseños para la mejora o el desarrollo de  espacios interiores para diversos usos (oficinas, establecimientos, lugares públicos, etc.).', 6),
(166, 'Ser técnico en gestión comercial y marketing.', 6),
(167, 'Colaborar con el médico en el cuidado de los  enfermos, aplicando conocimientos sobre el organismo humano, las funciones fisiológicas y el comportamiento de las personas.', 6),
(168, 'Ser actor de doblaje.', 6),
(169, 'Aplicar los conocimientos técnicos al campo de los seguros; calcular las operaciones financieras para hacer rentables los fondos económicos.', 6),
(170, 'Trabajar como investigador privado', 6),
(171, 'Atender a los pasajeros en vuelos de líneas aéreas o de barcos o cruceros.', 6),
(172, 'Ser teólogo.', 6),
(173, 'Custodiar establecimientos, oficinas, etc., para evitar robos y otros hechos delictivos. Colaborar en el transporte de mercancías valiosas o dinero', 6),
(174, 'Ejercer la profesión de especialista en Arte.', 6),
(175, 'Aplicar los conocimientos de Economía para interpretar situaciones y aplicar soluciones que resuelvan problemas prácticos en empresas; establecer planes para el crecimiento de las mismas.', 6),
(176, 'Trabajar como técnico en trabajos forestales y  conservación del medio ambiente.', 6),
(177, 'Analizar las técnicas y métodos de enseñanza e idear nuevos procedimientos didácticos, o dirigir y organizar centros educativos.', 6),
(178, 'Ser médico', 6),
(179, 'Dibujar, o diseñar con ordenador, elementos para decoración cerámica, estampación textil, escaparatismo o mobiliario.', 6),
(180, 'Ser especialista del Ejército.', 6);